package com.wsp.xjdbc.core.connection;

import com.wsp.xjdbc.core.MasterSlaveDataSource;
import com.wsp.xjdbc.core.XJdbcContext;

import com.wsp.xjdbc.core.statement.StandardMasterSlaveStatement;
import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;

/**
 * Title :标准的读写数据源连接实现,通过决策数据源获取数据源连接
 * Description: 实现JDBC Connection所有方法</br>
 * @author <a href=mailto:wangsongpeng@jd.com>王宋鹏</a>
 * @since 2018/07/20
 */
public class StandardMasterSlaveConnection extends AbstractMasterSlaveConnection{

    private static final Logger log = LoggerFactory.getLogger(StandardMasterSlaveConnection.class);

    public StandardMasterSlaveConnection(MasterSlaveDataSource dataSource){
           this(dataSource,null,null);
    }

    public StandardMasterSlaveConnection(MasterSlaveDataSource dataSource, String userName, String passWord){
        super(userName,passWord);
        this.masterSlaveDataSource = dataSource;
    }

    @Override
    public Connection determineRealConnection(String sql) {
        if(null != targetConnection){
            return targetConnection;
        }
        try {
            if(StringUtils.isBlank(userName) && StringUtils.isBlank(passWord)){
                targetConnection = masterSlaveDataSource.determineRealDataSource(sql).getConnection();
            }else{
                targetConnection = masterSlaveDataSource.determineRealDataSource(sql).getConnection(userName,passWord);
            }
            replayMethodsInvocation(targetConnection);
        }catch (Exception e){
            log.error("determineRealConnection Happen Exception",e);
        }
        return targetConnection;
    }

    @Override
    public Statement createStatement() throws SQLException {
        return new StandardMasterSlaveStatement(this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return determineRealConnection(sql).prepareStatement(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        return determineRealConnection(sql).prepareCall(sql);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
         return new StandardMasterSlaveStatement(this,resultSetType,resultSetConcurrency);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return determineRealConnection(sql).prepareStatement(sql,resultSetType,resultSetConcurrency);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return determineRealConnection(sql).prepareCall(sql,resultSetType,resultSetConcurrency);
    }


    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return new StandardMasterSlaveStatement(this,resultSetType,resultSetConcurrency,resultSetHoldability);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return determineRealConnection(sql).prepareStatement(sql,resultSetType,resultSetConcurrency,resultSetHoldability);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return determineRealConnection(sql).prepareCall(sql,resultSetType,resultSetConcurrency,resultSetHoldability);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return determineRealConnection(sql).prepareStatement(sql,autoGeneratedKeys);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return determineRealConnection(sql).prepareStatement(sql,columnIndexes);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return determineRealConnection(sql).prepareStatement(sql,columnNames);
    }

    @Override
    public void close() throws SQLException {
        XJdbcContext.getContext().setOnlyMasterFlag(Boolean.FALSE);
        super.close();
    }
}
